# Generated by Django 4.2 on 2023-04-19 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.TextField(default='', max_length=50)),
                ('endereco', models.TextField(max_length=50)),
                ('destino', models.TextField(max_length=50)),
                ('turno', models.TextField(max_length=20)),
                ('dia', models.TextField(max_length=30)),
                ('status', models.TextField(default='Análise', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('numero_casa', models.IntegerField(null=True)),
                ('rua', models.TextField(max_length=25, null=True)),
                ('bairro', models.TextField(max_length=20, null=True)),
                ('complemento', models.TextField(max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
