# Generated by Django 4.2 on 2023-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0002_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteescolar',
            name='nome',
            field=models.EmailField(default='User.first_name', max_length=50),
        ),
    ]
