# Generated by Django 4.2 on 2023-04-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0003_transporteescolar_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteescolar',
            name='nome',
            field=models.TextField(default='', max_length=50),
        ),
    ]
