# Generated by Django 4.2 on 2023-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0004_alter_transporteescolar_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporteescolar',
            name='nome',
        ),
        migrations.AddField(
            model_name='transporteescolar',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
    ]
