# Generated by Django 4.2 on 2023-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0005_remove_transporteescolar_nome_transporteescolar_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporteescolar',
            name='cpf',
        ),
        migrations.AddField(
            model_name='transporteescolar',
            name='nome',
            field=models.TextField(default='', max_length=50),
        ),
    ]
