# Generated by Django 4.0.5 on 2023-05-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0006_remove_transporteescolar_cpf_transporteescolar_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(default='', max_length=50)),
                ('email', models.TextField(default='', max_length=50)),
                ('musica', models.TextField(default='', max_length=50)),
                ('banda', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
